### ISSUE TITLE
control of video output size

### ISSUE THREAD

**Issue by JessePimenta** [maua-maua-maua/maua#3]
is there a way to change the w/h of a video output? currently using an init video that is 1024 x 512, and when i try to change output size in the code, (512,512) it gives me this:

RuntimeError: The size of tensor a (512) must match the size of tensor b (1024) at non-singleton dimension 2

If i try changing either width or height I am presented with this. I may just be trying to modify the wrong param - apologies in advance!

**Comment by JCBrouwer** [comment]
I'm assuming you're using this [Colab Notebook](https://colab.research.google.com/drive/12lZVcq363lz9HMY-eI3raV1PKilHkUX8)?

Looks like it was a bug related to caching. Could you try again with the most recent version?

In the future it really helps to say how you're running the code (e.g. in colab or locally via CLI) and also include the full stack trace rather than just the error. That makes it a lot easier to fix the issues as the rest of the stuff printed above the error has context clues to help hunt down the part that's broken.

**Comment by JessePimenta** [comment]
My apologies, you were correct to assume that it is from the colab notebook. 

I'll try again with that link and see if that clears it up, and inlcude the full stack trace if anything else comes up.
Really appreciate your work and vision on maua, having a lot of fun so far.

**Comment by JCBrouwer** [comment]
I'm going to close this for now, but feel free to re-open if it's still not working on your end.

Thanks for reporting!
